
package br.com.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-09-20T01:59:47.733-03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.com.br/")
public class Exception_Exception extends java.lang.Exception {
    
    private br.com.ws.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, br.com.ws.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, br.com.ws.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public br.com.ws.Exception getFaultInfo() {
        return this.exception;
    }
}
