package br.com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-09-20T01:59:47.778-03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "OnlinePublicAlfrescoService", 
                  wsdlLocation = "http://www2.sefaz.ce.gov.br/AlfrescoWS-ejb/public?wsdl",
                  targetNamespace = "http://ws.com.br/") 
public class OnlinePublicAlfrescoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.com.br/", "OnlinePublicAlfrescoService");
    public final static QName PublicPort = new QName("http://ws.com.br/", "publicPort");
    static {
        URL url = null;
        try {
            url = new URL("http://www2.sefaz.ce.gov.br/AlfrescoWS-ejb/public?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OnlinePublicAlfrescoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www2.sefaz.ce.gov.br/AlfrescoWS-ejb/public?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OnlinePublicAlfrescoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OnlinePublicAlfrescoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlinePublicAlfrescoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OnlinePublicAlfrescoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OnlinePublicAlfrescoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OnlinePublicAlfrescoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Public
     */
    @WebEndpoint(name = "publicPort")
    public Public getPublicPort() {
        return super.getPort(PublicPort, Public.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Public
     */
    @WebEndpoint(name = "publicPort")
    public Public getPublicPort(WebServiceFeature... features) {
        return super.getPort(PublicPort, Public.class, features);
    }

}
